# Generated by Django 4.2.7 on 2025-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('summary', models.TextField()),
                ('key_points', models.JSONField()),
                ('difficulty', models.CharField(max_length=20)),
                ('bloom_level', models.CharField(max_length=20)),
                ('topic_graph', models.JSONField()),
                ('quiz_questions', models.JSONField()),
                ('tags', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1_text', models.TextField()),
                ('note2_text', models.TextField()),
                ('similarity_score', models.FloatField()),
                ('comparison_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
