# Generated by Django 4.2.7 on 2025-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteanalysis',
            name='applications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='noteanalysis',
            name='learning_objectives',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='noteanalysis',
            name='prerequisites',
            field=models.JSONField(default=list),
        ),
    ]
