# Generated by Django 4.2.7 on 2025-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_noteanalysis_applications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notecomparison',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='noteanalysis',
            name='session_key',
            field=models.CharField(db_index=True, default='anonymous', max_length=40),
        ),
        migrations.AddField(
            model_name='notecomparison',
            name='session_key',
            field=models.CharField(db_index=True, default='anonymous', max_length=40),
        ),
    ]
